services:
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - "expense_tracker_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  expense_tracker_data:
    name: expense_tracker_data
