import {
  Activity,
  Ambulance,
  Apple,
  BaggageClaim,
  Beef,
  CakeSlice,
  Car,
  CircleDollarSign,
  Cookie,
  CupSoda,
  Dog,
  Donut,
  Droplet,
  Dumbbell,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  Grid2X2,
  Guitar,
  Heart,
  House,
  Landmark,
  Microwave,
  MicVocal,
  Pencil,
  Phone,
  PiggyBank,
  Plane,
  PlugZap2,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  Umbrella,
  Users,
  Utensils,
} from "lucide-react";

export type IconListType = {
  [key: string]: React.ElementType;
};

const iconDictionary: IconListType = {
  utensils: Utensils,
  droplet: Droplet,
  plugZap2: PlugZap2,
  beef: Beef,
  landmark: Landmark,
  car: Car,
  shoppingBag: ShoppingBag,
  piggyBank: PiggyBank,
  cookie: Cookie,
  cupSoda: CupSoda,
  microwave: Microwave,
  shieldPlus: ShieldPlus,
  gamepad2: Gamepad2,
  umbrella: Umbrella,
  house: House,
  donut: Donut,
  baggageClaim: BaggageClaim,
  dog: Dog,
  fuel: Fuel,
  heart: Heart,
  micVocal: MicVocal,
  shirt: Shirt,
  ambulance: Ambulance,
  gift: Gift,
  grid2x2: Grid2X2,
  apple: Apple,
  cakeSlice: CakeSlice,
  plane: Plane,
  phone: Phone,
  dumbbell: Dumbbell,
  circleDollarSign: CircleDollarSign,
  activity: Activity,
  flower2: Flower2,
  pencil: Pencil,
  guitar: Guitar,
  users: Users,
};

export default iconDictionary;
