import {
  Activity,
  Ambulance,
  Apple,
  BaggageClaim,
  Beef,
  CakeSlice,
  Car,
  CircleDollarSign,
  Cookie,
  CupSoda,
  Dog,
  Donut,
  Droplet,
  Dumbbell,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  Grid2X2,
  Guitar,
  Heart,
  House,
  Landmark,
  Microwave,
  MicVocal,
  Pencil,
  Phone,
  PiggyBank,
  Plane,
  PlugZap2,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  Umbrella,
  Users,
  Utensils,
} from "lucide-react";

export type IconListType = {
  [key: string]: React.ElementType;
};

const iconDictionary: IconListType = {
  utensils: Utensils,
  droplet: Droplet,
  plugZap2: PlugZap2,
  beef: Beef,
  landmark: Landmark,
  car: Car,
  shoppingBag: ShoppingBag,
  piggyBank: PiggyBank,
  cookie: Cookie,
  cupSoda: CupSoda,
  microwave: Microwave,
  shieldPlus: ShieldPlus,
  "gamepad-2": Gamepad2,
  umbrella: Umbrella,
  house: House,
  dount: Donut,
  "baggage-claim": BaggageClaim,
  dog: Dog,
  fuel: Fuel,
  heart: Heart,
  "mic-vocal": MicVocal,
  shirt: Shirt,
  ambulance: Ambulance,
  gift: Gift,
  "grid-2x2": Grid2X2,
  apple: Apple,
  "cake-slice": CakeSlice,
  plane: Plane,
  phone: Phone,
  dumbbell: Dumbbell,
  "circle-dollar-sign": CircleDollarSign,
  activity: Activity,
  "flower-2": Flower2,
  pencil: Pencil,
  guitar: Guitar,
  users: Users,
};

export default iconDictionary;
